--- 
JB: 
  ASSET_PATH: false
  BASE_PATH: false
  analytics: 
    gauges: 
      site_id: "SITE ID"
    getclicky: 
      site_id: ~
    google: 
      tracking_id: UA-123-12
    mixpanel: 
      token: _MIXPANEL_TOKEN_
    piwik: 
      baseURL: myserver.tld/piwik
      idsite: "1"
    provider: google
  archive_path: /archive.html
  atom_path: /atom.xml
  categories_path: /categories.html
  comments: 
    disqus: 
      short_name: markoschuetzschmuck
    duoshuo: 
      short_name: jekyllbootstrap
    facebook: 
      appid: 123
      colorscheme: light
      num_posts: 5
      width: 580
    intensedebate: 
      account: 123abc
    livefyre: 
      site_id: ~
    provider: disqus
  rss_path: /rss.xml
  sharing: 
    provider: false
  tags_path: /tags.html
  version: "0.3.0"
author: 
  email: MarkoSchuetz@web.de
  feedburner: feedname
  github: MarkoSchuetz
  name: "Marko Schütz-Schmuck"
  twitter: username
exclude: 
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
highlighter: pygments
permalink: "/:categories/:year/:month/:day/:title"
production_url: "http://MarkoSchuetz.github.io"
tagline: "Site Tagline"
title: Blog
